development: &development
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: fftest
  host: /var/run/postgresql
  pool: 5
  username: fftest
  port: 5433
 
test: &test
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: sandbox_test
  host: localhost
  pool: 5
  username: srirangarajan
